import re

with open('../agents/ceo/service.go', 'r') as f:
    text = f.read()

# Update signature of ensureConversationGraph
text = text.replace('func (s *Service) ensureConversationGraph(threadID string) (threads.Thread, error) {', 'func (s *Service) ensureConversationGraph(threadID string, title string) (threads.Thread, error) {')

# Update call to ensureConversationGraph
text = text.replace('return s.ensureConversationGraph(threadID)', '''title := ""
if request.Context != nil {
if t, ok := request.Context["autoGeneratedTitle"].(string); ok {
title = t
}
}
return s.ensureConversationGraph(threadID, title)''')

text = text.replace('ProgramTitle:   fallbackProgramTitle(threadID),', 'ProgramTitle:   emptyFallback(title, fallbackProgramTitle(threadID)),')
text = text.replace('MissionTitle:   fallbackMissionTitle(threadID),', 'MissionTitle:   emptyFallback(title, fallbackMissionTitle(threadID)),')
text = text.replace('ThreadTitle:    fallbackThreadTitle(threadID),', 'Thimport re

with open('../agenit
with opbac    text = f.read()

# Update signature of ensus/
# Update signaturw')text = text.replace('fun

